name: "Rosas Action"
description: "My first Action"

runs:
  using: "composite"

  steps:
  - name: Hola guapa
    run: echo "Hola guapa!"
    shell: bash
  
  - name: whoami
    run: whoami
    shell: bash