name: Laravel CI (TBU in a Laravel project)

on: [push]

jobs:
    laravel-test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:latest
                ports:
                    - 3006:3006
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: laravel
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: PHP setup
              uses: shivammathur/setup-php@2.31.1
              with:
                php-version: latest
                extensions: mbstring, bcmath, pdo, pdo_mysql
            
            - name: Install packages
              run: composer install --no-interaction


