name: Test Composite Action

on:
    push:
        branches:
            test

jobs:
    local-action:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: Say Hi
              uses: ./.github/actions/my-action
              with:
                message: "GitHub Actions rocks!"