name: Test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: ls & install curl
              run: |
                ls -al
                sudo apt install curl
                curl https://google.com