name: Test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: ls
              run: ls -la

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.1.0
              with:
                node-version: latest
            
            - name: Node version
              run: node --version
            
            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.31.1
              with:
                php-version: latest
              
            - name: PHP version
              run: php --version                          