name: Workflow Dispatch

on: workflow_dispatch

jobs:
    wkf-dispatch:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4.2.2

            - name: LS
              run: ls -la