name: Using conditionals & artifacts

on: [push]

jobs:
    using-conditionals:
        runs-on: ubuntu-latest

        steps:
            - name: First step
              id: apt_update
              run: sudo apt update
            
            - name: Second step
              id: apt_install
              if: steps.apt_update.outcome == 'success'
              run: sudo apt install vim -y
            
            - name: Third step
              if: steps.apt_update.outcome == 'sucess' && steps.apt_update.outcome == 'fail'
              run: echo "You are wrong!"
    
    using-artifacts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Artifacts
              uses: actions/upload-artifact@v4.4.3
              if: failure()
              with:
                name: artifacts
                path: hola.txt

