name: Using Repository Variables

on:
  push:
      branches:
          - test

jobs:
    using-variables:
        runs-on: ubuntu-latest
        
        steps:
            - name: Test1
              run: echo "Install JDK version ${{ vars.JDK_VERSION}}"