name: Using Services

on: [push]

jobs:
    using-services:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MY_SQL_PASSWORD: my-pass$
                ports:
                    - 3306:3306
        
        steps:
            - name: Test 
              run: ls