name: Using Variables

on: [push]

jobs:
    using-variables:
        runs-on: ubuntu-latest

        env:
            MY_VAR: Mi variable de entorno en Job
        
        steps:
            - name: Test1
              run: echo "Valor $MY_VAR"

            - name: Test2
              env:
                MY_VAR: Mi variable de entorno en Step
              run: echo "Valor $MY_VAR"