name: Test Composite Action

on: [push]

jobs:
    local-action:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: Say Hi
              uses: ./.github/actions/my-action