name: Mi primer workflow

on: [push, pull_request]

jobs:
    prev:
        runs-on: ubuntu-latest

        steps:
        - name: pwd
          run: pwd
        
        - name: whoami
          run: whoami
        
        - name: hostname
          run: hostname


    hola:
        runs-on: ubuntu-latest
        needs: [prev]

        steps:
        - name: Primer step
          run: echo "Hola Mundo!"
        
        - name: Crear file
          run: touch hola.txt
        
        - name: Add content
          run: echo "Hola guapa!" > hola.text
        
        - name: Display text
          run: cat hola.txt


    adios:
        runs-on: ubuntu-latest
        needs: hola

        steps:
        - name: Segundo step
          run: echo "Adiós Mundo!"
