name: Mi primer workflow

on: [push]

jobs:
    hola:
        runs-on: ubuntu-latest

        steps:
        - name: Primer step
          run: echo "Hola Mundo!"
        
        - name: Crear file
          run: touch hola.txt

    adios:
        runs-on: ubuntu-latest

        steps:
        - name: Segundo step
          run: echo "Adiós Mundo!"
