name: Mi primer workflow

on:
    push:
        branches:
            - test
    
    pull_request:
        branches:
            - test 


jobs:
    prev:
        runs-on: ubuntu-latest

        steps:
        - name: pwd
          run: pwd
        
        - name: whoami
          run: whoami
        
        - name: hostname
          run: hostname


    hola:
        runs-on: ubuntu-latest
        needs: [prev]

        steps:
        - name: Primer step
          run: echo "Hola Mundo!"
        
        - name: Crear file
          run: touch hola.txt
        
        - name: Add content
          run: echo "Hola guapa!" > hola.text
        
        - name: Display text
          run: cat hola.txt


    adios:
        runs-on: ubuntu-latest
        needs: hola

        steps:
        - name: Segundo step
          run: echo "Adiós Mundo!"
 
          
    other:
        runs-on: ubuntu-latest
        needs: adios

        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        
        - name: ls
          run: ls -la